
[input]
base_directory = "output/"
files = [
    {path = "1-1-0-3-other.md", url = "#", title = "1-1-0-3-other", pdf = "1-1-0-3-other.pdf", type = "TODO" },
    {path = "1-1-1-4-other.md", url = "#", title = "1-1-1-4-other", pdf = "1-1-1-4-other.pdf", type = "TODO" },
    {path = "1-1-2-5-other.md", url = "#", title = "1-1-2-5-other", pdf = "1-1-2-5-other.pdf", type = "TODO" },
    {path = "1-1-2-6-example.md", url = "#", title = "1-1-2-6-example", pdf = "1-1-2-6-example.pdf", type = "TODO" },
    {path = "1-1-2-7-other.md", url = "#", title = "1-1-2-7-other", pdf = "1-1-2-7-other.pdf", type = "TODO" },
    {path = "1-1-2-8-example.md", url = "#", title = "1-1-2-8-example", pdf = "1-1-2-8-example.pdf", type = "TODO" },
    {path = "1-1-3-10-other.md", url = "#", title = "1-1-3-10-other", pdf = "1-1-3-10-other.pdf", type = "TODO" },
    {path = "1-1-3-11-example.md", url = "#", title = "1-1-3-11-example", pdf = "1-1-3-11-example.pdf", type = "TODO" },
    {path = "1-1-4-13-other.md", url = "#", title = "1-1-4-13-other", pdf = "1-1-4-13-other.pdf", type = "TODO" },
    {path = "1-1-4-14-example.md", url = "#", title = "1-1-4-14-example", pdf = "1-1-4-14-example.pdf", type = "TODO" },
    {path = "1-2-1-16-other.md", url = "#", title = "1-2-1-16-other", pdf = "1-2-1-16-other.pdf", type = "TODO" },
    {path = "1-2-1-17-example.md", url = "#", title = "1-2-1-17-example", pdf = "1-2-1-17-example.pdf", type = "TODO" },
    {path = "1-2-1-18-other.md", url = "#", title = "1-2-1-18-other", pdf = "1-2-1-18-other.pdf", type = "TODO" },
    {path = "1-2-2-19-theorem.md", url = "#", title = "1-2-2-19-theorem", pdf = "1-2-2-19-theorem.pdf", type = "TODO" },
    {path = "1-2-2-20-other.md", url = "#", title = "1-2-2-20-other", pdf = "1-2-2-20-other.pdf", type = "TODO" },
    {path = "1-2-2-21-theorem.md", url = "#", title = "1-2-2-21-theorem", pdf = "1-2-2-21-theorem.pdf", type = "TODO" },
    {path = "1-2-2-22-other.md", url = "#", title = "1-2-2-22-other", pdf = "1-2-2-22-other.pdf", type = "TODO" },
    {path = "1-2-2-23-remark.md", url = "#", title = "1-2-2-23-remark", pdf = "1-2-2-23-remark.pdf", type = "TODO" },
    {path = "1-2-2-25-theorem.md", url = "#", title = "1-2-2-25-theorem", pdf = "1-2-2-25-theorem.pdf", type = "TODO" },
    {path = "1-2-2-26-other.md", url = "#", title = "1-2-2-26-other", pdf = "1-2-2-26-other.pdf", type = "TODO" },
    {path = "1-2-2-27-theorem.md", url = "#", title = "1-2-2-27-theorem", pdf = "1-2-2-27-theorem.pdf", type = "TODO" },
    {path = "1-2-2-28-other.md", url = "#", title = "1-2-2-28-other", pdf = "1-2-2-28-other.pdf", type = "TODO" },
    {path = "1-2-2-29-remark.md", url = "#", title = "1-2-2-29-remark", pdf = "1-2-2-29-remark.pdf", type = "TODO" },
    {path = "1-2-2-30-other.md", url = "#", title = "1-2-2-30-other", pdf = "1-2-2-30-other.pdf", type = "TODO" },
    {path = "1-2-3-31-theorem.md", url = "#", title = "1-2-3-31-theorem", pdf = "1-2-3-31-theorem.pdf", type = "TODO" },
    {path = "1-2-3-32-other.md", url = "#", title = "1-2-3-32-other", pdf = "1-2-3-32-other.pdf", type = "TODO" },
    {path = "1-2-3-33-corollary.md", url = "#", title = "1-2-3-33-corollary", pdf = "1-2-3-33-corollary.pdf", type = "TODO" },
    {path = "1-2-3-34-other.md", url = "#", title = "1-2-3-34-other", pdf = "1-2-3-34-other.pdf", type = "TODO" },
    {path = "1-2-3-35-theorem.md", url = "#", title = "1-2-3-35-theorem", pdf = "1-2-3-35-theorem.pdf", type = "TODO" },
    {path = "1-2-3-36-other.md", url = "#", title = "1-2-3-36-other", pdf = "1-2-3-36-other.pdf", type = "TODO" },
    {path = "1-2-4-37-other.md", url = "#", title = "1-2-4-37-other", pdf = "1-2-4-37-other.pdf", type = "TODO" },
    {path = "1-2-4-38-theorem.md", url = "#", title = "1-2-4-38-theorem", pdf = "1-2-4-38-theorem.pdf", type = "TODO" },
    {path = "1-2-4-39-other.md", url = "#", title = "1-2-4-39-other", pdf = "1-2-4-39-other.pdf", type = "TODO" },
    {path = "1-2-5-40-other.md", url = "#", title = "1-2-5-40-other", pdf = "1-2-5-40-other.pdf", type = "TODO" },
    {path = "1-3-0-41-other.md", url = "#", title = "1-3-0-41-other", pdf = "1-3-0-41-other.pdf", type = "TODO" },
    {path = "1-3-1-42-other.md", url = "#", title = "1-3-1-42-other", pdf = "1-3-1-42-other.pdf", type = "TODO" },
    {path = "1-3-1-43-theorem.md", url = "#", title = "1-3-1-43-theorem", pdf = "1-3-1-43-theorem.pdf", type = "TODO" },
    {path = "1-3-1-44-other.md", url = "#", title = "1-3-1-44-other", pdf = "1-3-1-44-other.pdf", type = "TODO" },
    {path = "1-3-1-45-theorem.md", url = "#", title = "1-3-1-45-theorem", pdf = "1-3-1-45-theorem.pdf", type = "TODO" },
    {path = "1-3-1-46-other.md", url = "#", title = "1-3-1-46-other", pdf = "1-3-1-46-other.pdf", type = "TODO" },
    {path = "1-3-1-47-theorem.md", url = "#", title = "1-3-1-47-theorem", pdf = "1-3-1-47-theorem.pdf", type = "TODO" },
    {path = "1-3-1-48-other.md", url = "#", title = "1-3-1-48-other", pdf = "1-3-1-48-other.pdf", type = "TODO" },
    {path = "1-3-2-49-other.md", url = "#", title = "1-3-2-49-other", pdf = "1-3-2-49-other.pdf", type = "TODO" },
    {path = "1-3-2-50-theorem.md", url = "#", title = "1-3-2-50-theorem", pdf = "1-3-2-50-theorem.pdf", type = "TODO" },
    {path = "1-3-2-51-other.md", url = "#", title = "1-3-2-51-other", pdf = "1-3-2-51-other.pdf", type = "TODO" },
    {path = "1-3-3-52-other.md", url = "#", title = "1-3-3-52-other", pdf = "1-3-3-52-other.pdf", type = "TODO" },
    {path = "1-3-3-53-theorem.md", url = "#", title = "1-3-3-53-theorem", pdf = "1-3-3-53-theorem.pdf", type = "TODO" },
    {path = "1-3-3-54-other.md", url = "#", title = "1-3-3-54-other", pdf = "1-3-3-54-other.pdf", type = "TODO" },
    {path = "1-3-3-55-lemma.md", url = "#", title = "1-3-3-55-lemma", pdf = "1-3-3-55-lemma.pdf", type = "TODO" },
    {path = "1-3-3-56-other.md", url = "#", title = "1-3-3-56-other", pdf = "1-3-3-56-other.pdf", type = "TODO" }
]

[output]
filename = "mmi.st"
